import assert from 'node:assert/strict';
import { createLivekitVoiceJoin, createLivekitVoiceMonitorJoin, livekitAdapterConfig, livekitConfigured, livekitHttpUrl, livekitParticipantIdentity, livekitRoomName, livekitRoomOptions, voiceAdapterTransport } from './livekit-voice.mjs';

assert.equal(voiceAdapterTransport(), 'livekit');
assert.equal(voiceAdapterTransport('legacy'), 'legacy');
assert.equal(voiceAdapterTransport('anything else'), 'livekit');
assert.equal(livekitRoomName('a bad / session'), 'box-voice-abadsession');
assert.equal(livekitParticipantIdentity('hello'), 'caller-hello');
assert.equal(livekitHttpUrl('wss://example.livekit.cloud/'), 'https://example.livekit.cloud');
const config = livekitAdapterConfig({ url: 'wss://example.livekit.cloud', apiKey: 'key', apiSecret: 'secret' });
assert.equal(config.agentName, 'box-codex-voice');
assert.equal(livekitConfigured(config), true);
assert.equal(livekitConfigured({ ...config, apiSecret: '' }), false);
const options = livekitRoomOptions({ config, vsid: 'call-123', metadata: { agent: 'codex' } });
assert.equal(options.maxParticipants, 2);
assert.equal(options.agents.length, 1);
assert.equal(options.agents[0].agentName, 'box-codex-voice');
assert.deepEqual(JSON.parse(options.metadata), { source: 'box-voice', vsid: 'call-123', agent: 'codex' });
const join = await createLivekitVoiceJoin({ config, vsid: 'call-123', metadata: { agent: 'codex' } });
assert.equal(join.room, 'box-voice-call-123');
assert.equal(join.roomSid, '');
const claims = JSON.parse(Buffer.from(join.token.split('.')[1], 'base64url').toString('utf8'));
assert.equal(claims.roomConfig.name, 'box-voice-call-123');
assert.equal(claims.roomConfig.maxParticipants, 2);
assert.equal(claims.roomConfig.agents[0].agentName, 'box-codex-voice');
const monitor = await createLivekitVoiceMonitorJoin({ config, roomName: 'box-voice-call-123' });
assert.equal(monitor.room, 'box-voice-call-123');
assert.match(monitor.identity, /^monitor-/);
const monitorClaims = JSON.parse(Buffer.from(monitor.token.split('.')[1], 'base64url').toString('utf8'));
assert.equal(monitorClaims.video.roomJoin, true);
assert.equal(monitorClaims.video.canPublish, false);
assert.equal(monitorClaims.video.canSubscribe, true);
assert.equal(monitorClaims.video.canPublishData, false);
assert.equal(monitorClaims.roomConfig, undefined);
console.log('livekit voice helpers: ok');
